name: Publish Rheo.Storage NuGet Package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-test-pack-publish:
    runs-on: windows-latest

    env:
      Solution_Name: Rheo.sln
      Storage_Project_Path: Rheo.Storage\Rheo.Storage.csproj
      Test_Project_Path: Rheo.Test\Rheo.Test.csproj

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore ${{ env.Solution_Name }}

    - name: Build solution
      run: dotnet build ${{ env.Solution_Name }} --configuration Release --no-restore

    - name: Run tests
      run: dotnet test ${{ env.Test_Project_Path }} --configuration Release --no-build --verbosity normal --filter "Category=Storage"

    - name: NuGet Publisher
      # You may pin to the exact commit or the version.
      # uses: Jacup/publish-nuget@0d7b0c6f119fadaf9c3e2bcfcbb3bf3a1c439864
      uses: Jacup/publish-nuget@v2.6.0
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: env.Storage_Project_Path
        # API key to authenticate with NuGet server
        NUGET_KEY: secrets.NUGET_API_KEY
          
