name: Publish Rheo.Storage NuGet Package

on:
  push:
    branches: [ "master" ]
    paths:
      - 'Rheo.Storage/**' # only trigger on changes to Rheo.Storage project
    tags:
      - 'v*.*.*' # matches version tags like v1.2.3

jobs:
  build-test-pack-publish:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.101

    - name: Build, test, pack, and publish NuGet package artifact
      shell: pwsh
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: .\build.ps1 -Publish -ApiKey $env:NUGET_API_KEY
